####  Pre-processing (1) Sampling (2)Handling Missing Data (3) Remodeling (4) Dummy variables (5) Missing Data (6) Normalization

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

""" many algorithms will execute faster with smaller samples.Accurate models can often be built with as few as several thousand records. Hence, we will want to sample a subset of records for model building."""

In [26]:
#Read a csv file to a dataFrame WestRox
housing_df = pd.read_csv('https://raw.githubusercontent.com/reisanar/datasets/master/WestRoxbury.csv')

In [8]:
housing_df.to_csv('E:/WestRoxbury.csv')   # writing to E drive

In [6]:
import os #operating system library os
os.chdir("E:")  #change directory to E

In [7]:
#!dir *.*   #  ! mark invokes disk operating system command

In [8]:
housing_df.head()

TOTAL VALUE    TAX  LOT SQFT   YR BUILT  GROSS AREA   LIVING AREA  FLOORS   \
0         344.2  4330       9965      1880         2436         1352      2.0   
1         412.6  5190       6590      1945         3108         1976      2.0   
2         330.1  4152       7500      1890         2294         1371      2.0   
3         498.6  6272      13773      1957         5032         2608      1.0   
4         331.5  4170       5000      1910         2370         1438      2.0   

   ROOMS  BEDROOMS   FULL BATH  HALF BATH  KITCHEN  FIREPLACE REMODEL  
0      6          3          1          1        1          0    None  
1     10          4          2          1        1          0  Recent  
2      8          4          1          1        1          0    None  
3      9          5          1          1        1          1    None  
4      7          3          2          0        1          0    None

In [9]:
housing_df.head(2)

TOTAL VALUE    TAX  LOT SQFT   YR BUILT  GROSS AREA   LIVING AREA  FLOORS   \
0         344.2  4330       9965      1880         2436         1352      2.0   
1         412.6  5190       6590      1945         3108         1976      2.0   

   ROOMS  BEDROOMS   FULL BATH  HALF BATH  KITCHEN  FIREPLACE REMODEL  
0      6          3          1          1        1          0    None  
1     10          4          2          1        1          0  Recent

In [10]:
# random sample of 5 observations
housing_df.sample(5)

TOTAL VALUE    TAX  LOT SQFT   YR BUILT  GROSS AREA   LIVING AREA  \
4558         383.5  4824       5500      1913         2853         1706   
425          316.7  3984       6004      1960         2845         1726   
5222         405.6  5102       6219      1935         3053         1752   
1361         427.0  5371       4080      1988         4374         1968   
5101         479.4  6030       5900      1920         3272         1871   

      FLOORS   ROOMS  BEDROOMS   FULL BATH  HALF BATH  KITCHEN  FIREPLACE  \
4558      2.0      7          4          1          0        1          0   
425       1.0      7          3          1          1        1          0   
5222      2.0      8          3          1          0        1          1   
1361      1.5      6          3          2          0        1          1   
5101      2.0      8          4          1          1        1          1   

     REMODEL  
4558  Recent  
425   Recent  
5222    None  
1361    None  
5101    None

In [28]:
type(housing_df.REMODEL.values)

numpy.ndarray

In [29]:
housing_df.REMODEL.dtype

dtype('O')

In [31]:
type(housing_df.ROOMS.values)

numpy.ndarray

In [32]:
housing_df.ROOMS.dtype

dtype('int64')

In [13]:
housing_df.sample(5)

TOTAL VALUE    TAX  LOT SQFT   YR BUILT  GROSS AREA   LIVING AREA  \
1760         345.3  4343       4114      1965         2420         1600   
1478         341.2  4292       5000      1910         2058         1095   
378          353.5  4447       5885      1988         2418         1930   
2483         398.6  5014       5024      1930         2506         1576   
4564         351.9  4426       6278      1965         2804         1260   

      FLOORS   ROOMS  BEDROOMS   FULL BATH  HALF BATH  KITCHEN  FIREPLACE  \
1760      2.0      8          4          1          1        1          1   
1478      1.5      6          2          1          1        1          0   
378       1.0      9          4          2          0        2          0   
2483      2.0      7          3          1          1        1          0   
4564      1.0      6          2          1          1        1          1   

     REMODEL  
1760    None  
1478     Old  
378     None  
2483    None  
4564    None

#### Oversampling Rare Events in Classification Tasks

If the event we are interested in classifying is rare, for example, customers purchasing a
product in response to a mailing, or fraudulent credit card transactions, sampling a
random subset of records may yield so few events (e.g., purchases) that we have little
information on them. We would end up with lots of data on nonpurchasers and nonfraudulent
transactions but little on which to base a model that distinguishes purchasers
from nonpurchasers or fraudulent from non-fraudulent. In such cases, we would want
our sampling procedure to overweight the rare class (purchasers or frauds) relative to the
majority class (nonpurchasers, non-frauds) so that our sample would end up with a
healthy complement of purchasers or frauds.
Assuring an adequate number of responder or “success” cases to train the model is just
part of the picture. A more important factor is the costs of misclassification. Whenever
the response rate is extremely low, we are likely to attach more importance to identifying
a responder than to identifying a non-responder. In direct-response advertising (whether
by traditional mail, e-mail, or web advertising), we may encounter only one or two
responders for every hundred records—the value of finding such a customer far
outweighs the costs of reaching him or her. In trying to identify fraudulent transactions,
or customers unlikely to repay debt, the costs of failing to find the fraud or the nonpaying
customer are likely to exceed the cost of more detailed review of a legitimate transaction
or customer.
If the costs of failing to locate responders are comparable to the costs of misidentifying
responders as non-responders, our models would usually achieve highest overall accuracy
if they identified everyone as a non-responder (or almost everyone, if it is easy to identify
a few responders without catching many nonresponders). In such a case, the
misclassification rate is very low—equal to the rate of responders—but the model is of no
value.
More generally, we want to train our model with the asymmetric costs in mind so that the
algorithm will catch the more valuable responders, probably at the cost of “catching” and
misclassifying more non-responders as responders than would be the case if we assume
equal costs.

In [14]:
# oversample houses with over 10 rooms
weights = [0.9 if rooms > 10 else 0.01 for rooms in housing_df.ROOMS]
housing_df.sample(5, weights=weights)

TOTAL VALUE    TAX  LOT SQFT   YR BUILT  GROSS AREA   LIVING AREA  \
3626         412.0  5182       9740      1987         3006         1904   
4329         698.1  8782       6800      1908         5031         3461   
4841         394.2  4959       6971      1935         3024         1920   
2731         411.4  5175       4981      1930         2490         1374   
3837         476.1  5989       3620      1932         4118         3058   

      FLOORS   ROOMS  BEDROOMS   FULL BATH  HALF BATH  KITCHEN  FIREPLACE  \
3626      2.0      7          3          2          0        1          1   
4329      2.0     11          6          3          1        1          1   
4841      2.0      7          3          1          1        1          1   
2731      2.0      9          3          1          1        1          1   
3837      2.0     11          5          2          2        1          1   

     REMODEL  
3626    None  
4329  Recent  
4841    None  
2731    None  
3837  Recent

#### Reviewing variables in pandas

Preprocessing and Cleaning the Data
Types of Variables
There are several ways of classifying variables. Variables can be numerical or text
(character/string). They can be continuous (able to assume any real numerical value,
usually in a given range), integer (taking only integer values), categorical (assuming one
of a limited number of values), or date. Categorical variables can be either coded as
numerical (1, 2, 3) or text (payments current, payments not current, bankrupt).
Categorical variables can be unordered (called nominal variables) with categories such as
North America, Europe, and Asia; or they can be ordered (called ordinal variables) with
categories such as high value, low value, and nil value.
Continuous variables can be handled by most data mining routines with the exception of
the naive Bayes classifier, which deals exclusively with categorical predictor variables. The
machine learning roots of data mining grew out of problems with categorical outcomes;
the roots of statistics lie in the analysis of continuous variables. Sometimes, it is desirable
to convert continuous variables to categorical variables. This is done most typically in the
case of outcome variables, where the numerical variable is mapped to a decision (e.g.,
credit scores above a certain threshold mean “grant credit,” a medical test result above a
certain threshold means “start treatment”).


In [10]:
housing_df.columns # print a list of variables
# REMODEL needs to be converted to a categorical variable

Index(['TOTAL VALUE ', 'TAX', 'LOT SQFT ', 'YR BUILT', 'GROSS AREA ',
       'LIVING AREA', 'FLOORS ', 'ROOMS', 'BEDROOMS ', 'FULL BATH',
       'HALF BATH', 'KITCHEN', 'FIREPLACE', 'REMODEL'],
      dtype='object')

In [33]:
housing_df.columns = [s.strip().replace(" " , "_") for s in housing_df.columns]

In [34]:
type(housing_df['REMODEL'])

pandas.core.series.Series

In [35]:
housing_df.REMODEL.dtype

dtype('O')

In [36]:
housing_df.REMODEL = housing_df.REMODEL.astype("category")

In [23]:
housing_df.REMODEL.cat?

In [40]:
housing_df.REMODEL

0         None
1       Recent
2         None
3         None
4         None
         ...  
5797    Recent
5798      None
5799      None
5800      None
5801      None
Name: REMODEL, Length: 5802, dtype: category
Categories (3, object): [None, Old, Recent]

In [41]:
housing_df.REMODEL.cat.categories # Show number of categories

Index(['None', 'Old', 'Recent'], dtype='object')

In [42]:
housing_df.REMODEL.dtype # Check type of converted variable

CategoricalDtype(categories=['None', 'Old', 'Recent'], ordered=False)

#### Creating Dummy Variables in pandas

Handling Categorical Variables
Categorical variables can also be handled by most data mining routines, but often require
special handling. If the categorical variable is ordered (age group, degree of
creditworthiness, etc.), we can sometimes code the categories numerically (1, 2, 3, …) and
treat the variable as if it were a continuous variable. The smaller the number of
categories, and the less they represent equal increments of value, the more problematic
this approach becomes, but it often works well enough.
Nominal categorical variables, however, often cannot be used as is. In many cases, they
must be decomposed into a series of binary variables, called dummy variables. For
example, a single categorical variable that can have possible values of “student,”
“unemployed,” “employed,” or “retired” would be split into four separate dummy
variables:
Student—Yes/No
Unemployed—Yes/No
Employed—Yes/No
Retired—Yes/No
In many cases, only three of the dummy variables need to be used; if the values of three
are known, the fourth is also known. For example, given that these four values are the
only possible ones, we can know that if a person is neither student, unemployed, nor
employed, he or she must be retired. In some routines (e.g., linear regression and logistic
regression), you should not use all four variables—the redundant information will cause
the algorithm to fail. Note, also, that typical methods of creating dummy variables will
leave the original categorical variable intact; obviously you should not use both the
original variable and the dummies.

"""use drop_first=True to drop the first dummy variable
housing_df = pd.get_dummies(housing_df, prefix_sep=’_’, drop_first=True)
housing_df.columns
housing_df.loc[:, ’REMODEL_Old’:’REMODEL_Recent’].head(5) """

In [48]:
housing_df = pd.get_dummies(housing_df, prefix_sep="_")

In [49]:
housing_df.columns

Index(['TOTAL_VALUE', 'TAX', 'LOT_SQFT', 'YR_BUILT', 'GROSS_AREA',
       'LIVING_AREA', 'FLOORS', 'ROOMS', 'BEDROOMS', 'FULL_BATH', 'HALF_BATH',
       'KITCHEN', 'FIREPLACE', 'REMODEL_None', 'REMODEL_Old',
       'REMODEL_Recent'],
      dtype='object')

In [51]:
housing_df = pd.get_dummies(housing_df, prefix_sep="_", drop_first=True)

In [52]:
housing_df.columns

Index(['TOTAL_VALUE', 'TAX', 'LOT_SQFT', 'YR_BUILT', 'GROSS_AREA',
       'LIVING_AREA', 'FLOORS', 'ROOMS', 'BEDROOMS', 'FULL_BATH', 'HALF_BATH',
       'KITCHEN', 'FIREPLACE', 'REMODEL_None', 'REMODEL_Old',
       'REMODEL_Recent'],
      dtype='object')

In [53]:
housing_df.loc[:, "REMODEL_Old":"REMODEL_Recent"].head(5)

REMODEL_Old  REMODEL_Recent
0            0               0
1            0               1
2            0               0
3            0               0
4            0               0

Variable Selection
For one thing, the more variables we include and the more complex the model, the greater the
number of records we will need to assess relationships among the variables. Fifteen
records may suffice to give us a rough idea of the relationship between Y and a single
predictor variable X.

How Many Variables and How Much Data?A good rule of thumb is to have 10 records for every
predictor variable. Another rule, used by Delmaster and Hancock (2001, p. 68) for
classification procedures, is to have at least 6 × m × p records, where m is the number of
outcome classes and p is the number of variables.

Outliers
Values that lie far away from the bulk of the data are called outliers. The term far away is
deliberately left vague because what is or is not called an outlier is an arbitrary decision.
Analysts use rules of thumb such as “anything over three standard deviations away from
the mean is an outlier,” but no statistical rule can tell us whether such an outlier is the
result of an error. In this statistical sense, an outlier is not necessarily an invalid data
point, it is just a distant one.

All these are judgments best made by someone with domain knowledge, knowledge of the particular application being
considered: direct mail, mortgage finance, and so on, as opposed to technical knowledge
of statistical or data mining procedures. Statistical procedures can do little beyond
identifying the record as something that needs review.

Missing Values
Typically, some records will contain missing values. If the number of records with
missing values is small, those records might be omitted. However, if we have a large
number of variables, even a small proportion of missing values can affect a lot of records.

One option is to replace missing values using fairly simple substitutes
(e.g., mean, median). More sophisticated procedures do exist—for example, using linear
regression, based on other variables, to fill in the missing values.

The median is used for imputation, rather than the mean, to preserve the
integer nature of the counts for bedrooms.

To illustrate missing data procedures, we first convert a few entries for
bedrooms to NA’s. Then we impute these missing values using the median of the remaining values.

In [55]:
missingRows = housing_df.sample(10).index
missingRows

Int64Index([1441, 5437, 3432, 2299, 1524, 478, 427, 2745, 4449, 1336], dtype='int64')

In [58]:
housing_df.loc[missingRows, "BEDROOMS"] = np.nan  # removing the values for experiment

In [60]:
housing_df.loc[missingRows]

TOTAL_VALUE   TAX  LOT_SQFT  YR_BUILT  GROSS_AREA  LIVING_AREA  FLOORS  \
1441        298.1  3750      4052      1959        2463         1313     1.5   
5437        347.8  4375      7565      1945        2656         1248     1.0   
3432        336.4  4231      6237      1920        3276         1383     1.0   
2299        385.7  4852      7185      1920        2493         1426     2.0   
1524        518.3  6520      7877      1951        3644         2150     2.0   
478         311.2  3914      9551      1943        2508         1306     1.5   
427         340.1  4278      5712      1940        3336         2036     2.0   
2745        366.8  4614      3360      1921        2564         1560     2.0   
4449        274.7  3455      4800      1925        1804          902     1.0   
1336        294.2  3701      6289      1940        2194          952     1.0   

      ROOMS  BEDROOMS  FULL_BATH  HALF_BATH  KITCHEN  FIREPLACE  REMODEL_None  \
1441      6       NaN          2          0        1          1             0   
5437      6       NaN          1          1        1          0             1   
3432      5       NaN          1          0        1          0             1   
2299      7       NaN          1          0        1          1             1   
1524      9       NaN          2          0        1          0             0   
478       6       NaN          1          1        1          1             0   
427       7       NaN          1          1        1          1             1   
2745      6       NaN          1          0        1          1             1   
4449      4       NaN          1          0        1          0             1   
1336      6       NaN          1          0        1          0             1   

      REMODEL_Old  REMODEL_Recent  
1441            0               1  
5437            0               0  
3432            0               0  
2299            0               0  
1524            0               1  
478             1               0  
427             0               0  
2745            0               0  
4449            0               0  
1336            0               0

In [61]:
print("Number of rows with valid BEDROOMS values after setting to NAN: ",housing_df["BEDROOMS"].count())

Number of rows with valid BEDROOMS values after setting to NAN:  5792


In [62]:
# remove rows with missing values
reduced_df = housing_df.dropna()

In [63]:
print("Number of rows after removing rows with missing values: ",len(reduced_df))

Number of rows after removing rows with missing values:  5792


In [64]:
# replace the missing values using the median of the remaining values.
medianBedrooms = housing_df["BEDROOMS"].median()

In [65]:
medianBedrooms

3.0

In [66]:
housing_df.BEDROOMS = housing_df.BEDROOMS.fillna(value=medianBedrooms)

In [67]:
print("Number of rows with valid BEDROOMS values after filling NA values: ",housing_df["BEDROOMS"].count())

Number of rows with valid BEDROOMS values after filling NA values:  5802


##### pp64

Normalizing (Standardizing) and Rescaling Data
Some algorithms require that the data be normalized before the algorithm can be
implemented effectively. To normalize a variable, we subtract the mean from each value
and then divide by the standard deviation. This operation is also sometimes called
standardizing.

using the methods mean and std; (df - df.mean()) / df.std(). In effect, we
are expressing each value as the “number of standard deviations away from the mean,”
also called a z-score. An alternative is the class StandardScaler(), which is one of a
number different transformers available in scikit-learn. You can use the methods fit() or
fit_transform() to train the transformer on the training set and the method transform()
to apply on the validation set. The result of the transformation is no longer a pandas
dataframe, however, you can convert it back into one easily.

In [68]:
import pandas as pd

In [69]:
housing_df.mean()

TOTAL_VALUE        392.685715
TAX               4939.485867
LOT_SQFT          6278.083764
YR_BUILT          1936.744916
GROSS_AREA        2924.842123
LIVING_AREA       1657.065322
FLOORS               1.683730
ROOMS                6.994829
BEDROOMS             3.230265
FULL_BATH            1.296794
HALF_BATH            0.613926
KITCHEN              1.015340
FIREPLACE            0.739917
REMODEL_None         0.749052
REMODEL_Old          0.100138
REMODEL_Recent       0.150810
dtype: float64

In [70]:
housing_df.std()

TOTAL_VALUE         99.177414
TAX               1247.649118
LOT_SQFT          2669.707974
YR_BUILT            35.989910
GROSS_AREA         883.984726
LIVING_AREA        540.456726
FLOORS               0.444884
ROOMS                1.437657
BEDROOMS             0.845235
FULL_BATH            0.522040
HALF_BATH            0.533839
KITCHEN              0.122910
FIREPLACE            0.565108
REMODEL_None         0.433596
REMODEL_Old          0.300210
REMODEL_Recent       0.357894
dtype: float64

In [24]:
#housing_df...Now take out the last column which is categorical in nature...you will have error in " norm_df = (housing_df - housing_df.mean()) / housing_df.std()""

In [71]:
pp = housing_df.iloc[:,0:13]

In [73]:
pp.head(2)

TOTAL_VALUE   TAX  LOT_SQFT  YR_BUILT  GROSS_AREA  LIVING_AREA  FLOORS  \
0        344.2  4330      9965      1880        2436         1352     2.0   
1        412.6  5190      6590      1945        3108         1976     2.0   

   ROOMS  BEDROOMS  FULL_BATH  HALF_BATH  KITCHEN  FIREPLACE  
0      6       3.0          1          1        1          0  
1     10       4.0          2          1        1          0

In [74]:
house = (pp - pp.mean())/ pp.std()

In [75]:
house.head(2)

TOTAL_VALUE       TAX  LOT_SQFT  YR_BUILT  GROSS_AREA  LIVING_AREA  \
0    -0.488879 -0.488507  1.381019 -1.576690   -0.552998    -0.564458   
1     0.200795  0.200789  0.116835  0.229372    0.207196     0.590121   

     FLOORS     ROOMS  BEDROOMS  FULL_BATH  HALF_BATH   KITCHEN  FIREPLACE  
0  0.710905 -0.691980 -0.272428  -0.568528   0.723202 -0.124803  -1.309337  
1  0.710905  2.090325  0.910675   1.347035   0.723202 -0.124803  -1.309337

Normalizing is one way to bring all variables to the same scale. Another popular approach
is rescaling each variable to a [0, 1] scale. This is done by subtracting the minimum value
and then dividing by the range. Subtracting the minimum shifts the variable origin to
zero. Dividing by the range shrinks or expands the data to the range [0, 1]. In pandas, use
the expression (df-df.min())/ (df.max()-df.min()).

In [76]:
#Rescaling in Pandas
norm_df = (pp - pp.min()) / (pp.max() - pp.min())

In [77]:
norm_df.head(2)

TOTAL_VALUE       TAX  LOT_SQFT  YR_BUILT  GROSS_AREA  LIVING_AREA  FLOORS  \
0     0.214953  0.215015  0.197472  0.934858    0.220237     0.177220     0.5   
1     0.276420  0.276448  0.123156  0.967181    0.311878     0.307628     0.5   

      ROOMS  BEDROOMS  FULL_BATH  HALF_BATH  KITCHEN  FIREPLACE  
0  0.272727     0.250       0.00   0.333333      0.0        0.0  
1  0.636364     0.375       0.25   0.333333      0.0        0.0

In pandas, use the expression (df-df.min())/ (df.max()-df.min()). 
The corresponding scikit-learn
transformer is MinMaxScaler.
To consider why normalizing or scaling to [0, 1] might be necessary, consider the case of
clustering. Clustering typically involves calculating a distance measure that reflects how
far each record is from a cluster center or from other records. With multiple variables,
different units will be used: days, dollars, counts, and so on. If the dollars are in the
thousands and everything else is in the tens, the dollar variable will come to dominate the
distance measure. Moreover, changing units from, say, days to hours or months, could
alter the outcome completely.

Standardization of datasets is a common requirement for many machine learning estimators implemented in scikit-learn; they might behave badly if the individual features do not more or less look like standard normally distributed data:
Gaussian with zero mean and unit variance.In practice we often ignore the shape of the distribution and just transform the data to center it by removing the mean value of each feature, then scale it by dividing non-constant features by their standard deviation.

In [90]:
from sklearn import preprocessing

In [92]:
X_train = np.array([[ 1., -1.,  2.],
...                     [ 2.,  0.,  0.],
...                     [ 0.,  1., -1.]])
                   

In [93]:
X_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [94]:
X_scaled = preprocessing.scale(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [95]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [96]:
X_scaled.std(axis=0)

array([1., 1., 1.])

The preprocessing module further provides a utility class StandardScaler that implements the Transformer API to compute the mean and standard deviation on a training set so as to be able to later reapply the same transformation on the testing set. 
This class is hence suitable for use in the early steps of a sklearn.pipeline.Pipeline:

In [97]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [98]:
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [99]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [100]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [101]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [102]:
X_test = [[-1., 1., 0.]]

In [103]:
scaler.transform(X_test)

array([[-2.44948974,  1.22474487, -0.26726124]])

It is possible to disable either centering or scaling by either passing with_mean=False or with_std=False to the constructor of StandardScaler.

In [105]:
scaler.fit_transform(housing_df)

array([[-0.48892073, -0.48854954,  1.38113758, ...,  0.57880973,
        -0.33358861, -0.42141767],
       [ 0.20081186,  0.20080624,  0.11684541, ..., -1.72768345,
        -0.33358861,  2.37294272],
       [-0.63110245, -0.63123015,  0.45773604, ...,  0.57880973,
        -0.33358861, -0.42141767],
       ...,
       [ 0.13930062,  0.13908485,  0.3446053 , ...,  0.57880973,
        -0.33358861, -0.42141767],
       [-0.84689598, -0.84685422,  0.22922693, ...,  0.57880973,
        -0.33358861, -0.42141767],
       [ 0.55374521,  0.55349989,  0.42252316, ...,  0.57880973,
        -0.33358861, -0.42141767]])

In [106]:
norm_df = pd.DataFrame(scaler.fit_transform(housing_df),index=housing_df.index, columns=housing_df.columns)